name: Python CI

on:
  push:
    branches: [ main ] # Запускати при push у гілку main
  pull_request:
    branches: [ main ] # Також запускати при pull request до гілки main

jobs:
  build:
    runs-on: ubuntu-latest # Використовувати останню версію Ubuntu

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11'] # Матриця для тестування на різних версіях Python

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Дія для клонування репозиторію

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 # Дія для налаштування Python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest # Встановлюємо pytest, якщо він не в requirements.txt

    - name: Run tests
      run: |
        ls -R  # Покаже структуру файлів
        pytest
